version: 2
jobs:
  build:
    branches:
      only:
        - master
    deploy:
      steps:
        - run: ssh -o "StrictHostKeyChecking no" root@134.209.92.164 "cd ~/performance-matters-1819; git pull; npm install; forever start app.js"